services:
    reverse-proxy:
        image: traefik:latest
        command:
            - "--api.insecure=true"
            - "--providers.docker"
            - "--entrypoints.web.address=:80"
        ports:
          - "8000:80"
          - "8080:8080"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
    user-service:
        build: user-service
        ports:
          - "8001:8000"
        volumes:
            - ./user-service:/app
        command: uvicorn user_service.main:app --host 0.0.0.0 --port 80 --reload
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.user-service.rule=Host(`127.0.0.1`) && PathPrefix(`/users/`)"
          - "traefik.http.services.user-service.loadbalancer.server.port=80"
