services:
    reverse-proxy:
        image: traefik:latest
        command:
            - "--api.insecure=true"
            - "--providers.docker"
        ports:
          - "8000:80"
          - "8080:8080"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock:ro"

    user-service:
        build: user-service
        ports:
          - "80:80"
        volumes:
            - ./user-service:/app
        command: uvicorn user_service.main:app --host 0.0.0.0 --port 80 --reload
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.user-service.rule=Host(`user.localhost`)"
        depends_on:
          - user-db
        networks:
          - user-service

    user-db:
        image: postgres:alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: user-service
        volumes:
          - pgdata:/var/lib/postgresql/data
        networks:
          - user-service


volumes:
    pgdata:
        driver: local

networks:
    user-service:
        driver: bridge